### ISSUE TITLE
error in test

### ISSUE THREAD

**Issue by wenboown** [wenboown/textual_inversion#2]
run cmd:

```
python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune.yaml \
               -t \
               --actual_resume /data1/bwen-data/textual_inversion/models/ldm/text2img-large/model.ckpt \
               -n 5000 \
               --gpus 1, \
               --data_root /data1/bwen-data/textual_inversion/img/bwen \
               --init_word Portrait
```

run env:

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  Tesla V100-PCIE...  Off  | 00000000:00:06.0 Off |                    0 |
> | N/A   38C    P0    37W / 250W |      0MiB / 16384MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   1  Tesla V100-PCIE...  Off  | 00000000:00:07.0 Off |                    0 |
> | N/A   35C    P0    35W / 250W |      0MiB / 16384MiB |      2%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> 

> ...
> pop from empty list
> Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0
> Running DDIM Sampling with 200 timesteps
> DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:17<00:00, 11.34it/s]
> Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0█████████████████████████████████████████████████████████████████████▍| 199/200 [00:17<00:00, 11.35it/s]
> Running DDIM Sampling with 200 timesteps
> DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:29<00:00,  6.82it/s]
> Epoch 48:  79%|▊| 100/127 [01:23<00:22,  1.20it/s, loss=0.131, v_num=0, train/loss_simple_step=0.115, train/loss_vlb_step=0.000862, train/loss_step=0.115, globAverage Epoch time: 83.30 seconds
> Average Peak memory 9279.21MiB
> Epoch 48:  80%|▊| 101/127 [01:23<00:21,  1.21it/s, loss=0.131, v_num=0, train/loss_simple_step=0.115, train/loss_vlb_step=0.000862, train/loss_step=0.115, glob
> Saving latest checkpoint...
> 
> Traceback (most recent call last):
>   File "main.py", line 811, in <module>
>     trainer.test(model, data)
>   File "/data1/bwen-data/anaconda3/envs/ldm-dbio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 911, in test
>     return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
>   File "/data1/bwen-data/anaconda3/envs/ldm-dbio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "/data1/bwen-data/anaconda3/envs/ldm-dbio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 954, in _test_impl
>     results = self._run(model, ckpt_path=self.tested_ckpt_path)
>   File "/data1/bwen-data/anaconda3/envs/ldm-dbio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1128, in _run
>     verify_loop_configurations(self)
>   File "/data1/bwen-data/anaconda3/envs/ldm-dbio/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 42, in verify_loop_configurations
>     __verify_eval_loop_configuration(trainer, model, "test")
>   File "/data1/bwen-data/anaconda3/envs/ldm-dbio/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 186, in __verify_eval_loop_configuration
>     raise MisconfigurationException(f"No `{loader_name}()` method defined to run `Trainer.{trainer_method}`.")
> pytorch_lightning.utilities.exceptions.MisconfigurationException: No `test_dataloader()` method defined to run `Trainer.test`.

**Comment by wenboown** [comment]
it is just reaching the end of training. I think we can just set "--no_test" flag to skip the test step.

Ref: https://github.com/rinongal/textual_inversion/issues/36
